### ISSUE TITLE
I know this emulator is like old, but...

### ISSUE THREAD

**Issue by Giv0** [peteward44/WebNES#4]
Hiya!  i LOVE this emulator!  it allows me to play nes games on a chromebook offline!  anyway, i have a couple things that should get fixed.

1.  i get an "incorrect nes header" error when using the folder icon to load roms.  dragging works, but lags my chromebook.  please fix if possible for ease of use.

2.  i get sometimes a "mapper _insert number here_ is not supported."  I don't know what it means, but could you please fix it to support mapper _insert number here_.  I would like to not have to find another lost levels rom.

Thanks if you can fix!  

P.S. could you make a snes emulator EXACTLY like this nes emulator.  (and call it webSNES?)

**Comment by andymikulski** [comment]
>mapper [insert number here]

What is the number? Hard to fix the mapper if you don't say which one you need.

**Comment by peteward44** [comment]
Thankyou for your feedback! I will look into the opening the rom via the folder icon for you when i get time.

Like Andy said; we need to know the number ID of the mapper in order to see if we can add it to the supported mappers list. I assume you are trying to load one of the Super Mario Brothers Lost Levels ROMs? I looked and found "ZZZ_UNK_Super Mario Bros 3 - Lost Levels.nes" and that worked OK.

I did consider writing a web-based SNES emulator, however RetroArch (as well as other large emulation projects) are starting to use cross-compilers to build web based versions of their projects. Which kinda makes my own thing redundant. You can check out RetroArch's web based SNES emulator here https://toadking.com/retroarch/

**Comment by Dhill23000** [comment]
Pls Pls make this the  I use your nes emulator at school because the others are blocked. I would really boost you if you make the exact version for the snes emulator
